# Generated by Django 4.2 on 2023-04-25 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Shaxar nomi')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Shaxar nomi',
                'verbose_name_plural': 'Shaxarlar nomlari',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Dasturlash tili')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Dasturlash tili',
                'verbose_name_plural': 'Dasturlash tilllari',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Vakansiya nomi')),
                ('company', models.CharField(max_length=250, verbose_name='Kompaniya')),
                ('description', models.TextField(verbose_name='Vakansiya tasnifi')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.city', verbose_name='Shaxar')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.language', verbose_name='Dasturlash tili')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-timestamp'],
            },
        ),
    ]
