# Generated by Django 4.2 on 2023-04-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Xato',
                'verbose_name_plural': 'Xatolar',
            },
        ),
    ]
