# Generated by Django 4.2 on 2023-04-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Vakansiya nomi')),
                ('company', models.CharField(max_length=250, verbose_name='Kompaniya')),
                ('description', models.TextField(verbose_name='Vakansiya tasnifi')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.city', verbose_name='Shaxar')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.language', verbose_name='Dasturlash tili')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-timestamp'],
            },
        ),
    ]
